Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Customer
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH